package gui.tutor.profile;

import gui.TutorPanelContainer;
import java.awt.Color;
import tutormanagementsystem.Tutor;

public class TutorProfileRightMenu extends javax.swing.JPanel {
    private TutorPanelContainer frame;
    private Tutor tutor;

    public TutorProfileRightMenu(TutorPanelContainer frame, Tutor tutor) {
        initComponents();
        this.frame = frame;
        this.tutor = tutor;

        frame.navigateContentPanel(new TutorUpdateProfilePnl(frame, tutor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_rightMenu = new javax.swing.JPanel();
        pnl_updateProfile = new javax.swing.JPanel();
        lbl_updateProfile = new javax.swing.JLabel();
        pnl_changePassword = new javax.swing.JPanel();
        lbl_changePassword = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_rightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnl_updateProfile.setBackground(new java.awt.Color(63, 91, 135));
        pnl_updateProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_updateProfileMouseClicked(evt);
            }
        });

        lbl_updateProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_updateProfile.setForeground(new java.awt.Color(255, 255, 255));
        lbl_updateProfile.setText("Update Profile");

        javax.swing.GroupLayout pnl_updateProfileLayout = new javax.swing.GroupLayout(pnl_updateProfile);
        pnl_updateProfile.setLayout(pnl_updateProfileLayout);
        pnl_updateProfileLayout.setHorizontalGroup(
            pnl_updateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_updateProfileLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_updateProfile)
                .addGap(55, 55, 55))
        );
        pnl_updateProfileLayout.setVerticalGroup(
            pnl_updateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_updateProfileLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_updateProfile)
                .addGap(17, 17, 17))
        );

        pnl_changePassword.setBackground(new java.awt.Color(39, 56, 83));
        pnl_changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_changePasswordMouseClicked(evt);
            }
        });

        lbl_changePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_changePassword.setForeground(new java.awt.Color(255, 255, 255));
        lbl_changePassword.setText("Change Password");

        javax.swing.GroupLayout pnl_changePasswordLayout = new javax.swing.GroupLayout(pnl_changePassword);
        pnl_changePassword.setLayout(pnl_changePasswordLayout);
        pnl_changePasswordLayout.setHorizontalGroup(
            pnl_changePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_changePasswordLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_changePassword)
                .addGap(44, 44, 44))
        );
        pnl_changePasswordLayout.setVerticalGroup(
            pnl_changePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_changePasswordLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_changePassword)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_rightMenuLayout = new javax.swing.GroupLayout(pnl_rightMenu);
        pnl_rightMenu.setLayout(pnl_rightMenuLayout);
        pnl_rightMenuLayout.setHorizontalGroup(
            pnl_rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_updateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_changePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_rightMenuLayout.setVerticalGroup(
            pnl_rightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_rightMenuLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(pnl_updateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        add(pnl_rightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_updateProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_updateProfileMouseClicked
        pnl_updateProfile.setBackground(new Color(63,91,135));
        pnl_changePassword.setBackground(new Color(39,56,83));

        frame.navigateContentPanel(new TutorUpdateProfilePnl(frame, tutor));
    }//GEN-LAST:event_pnl_updateProfileMouseClicked

    private void pnl_changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_changePasswordMouseClicked
        pnl_changePassword.setBackground(new Color(63,91,135));
        pnl_updateProfile.setBackground(new Color(39,56,83));

        frame.navigateContentPanel(new TutorChangePasswordPnl(frame, tutor));
    }//GEN-LAST:event_pnl_changePasswordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_changePassword;
    private javax.swing.JLabel lbl_updateProfile;
    private javax.swing.JPanel pnl_changePassword;
    private javax.swing.JPanel pnl_rightMenu;
    private javax.swing.JPanel pnl_updateProfile;
    // End of variables declaration//GEN-END:variables
}
