package gui.tutor.profile;

import gui.TutorPanelContainer;

import java.util.Arrays;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import tutormanagementsystem.Main;
import tutormanagementsystem.Tutor;

public class TutorChangePasswordPnl extends javax.swing.JPanel {
    private TutorPanelContainer frame;
    private Tutor tutor;

    public TutorChangePasswordPnl(TutorPanelContainer frame, Tutor tutor) {
        initComponents();
        this.frame = frame;
        this.tutor = tutor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlUpdatePassword = new javax.swing.JPanel();
        lblOldPassword = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JPasswordField();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        lblConfirmNewPassword = new javax.swing.JLabel();
        txtConfirmNewPassword = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlUpdatePassword.setBackground(new java.awt.Color(242, 242, 242));

        lblOldPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOldPassword.setText("Old Password:");

        txtOldPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtOldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOldPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNewPassword.setText("New Password:");

        txtNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNewPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNewPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblConfirmNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConfirmNewPassword.setText("Confirm New Password:");

        txtConfirmNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtConfirmNewPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConfirmNewPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 43));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUpdatePasswordLayout = new javax.swing.GroupLayout(pnlUpdatePassword);
        pnlUpdatePassword.setLayout(pnlUpdatePasswordLayout);
        pnlUpdatePasswordLayout.setHorizontalGroup(
            pnlUpdatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdatePasswordLayout.createSequentialGroup()
                .addGroup(pnlUpdatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdatePasswordLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdatePasswordLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnlUpdatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlUpdatePasswordLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(pnlUpdatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConfirmNewPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                    .addComponent(lblConfirmNewPassword)))
                            .addComponent(txtNewPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOldPassword)
                            .addComponent(txtOldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNewPassword))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlUpdatePasswordLayout.setVerticalGroup(
            pnlUpdatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdatePasswordLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblOldPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblNewPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblConfirmNewPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnUpdate)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightBgLayout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(pnlUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(33, 33, 33)
                .addComponent(pnlUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Check if empty
        if (!String.valueOf(txtOldPassword.getPassword()).isEmpty() && !String.valueOf(txtNewPassword.getPassword()).isEmpty() && !String.valueOf(txtConfirmNewPassword.getPassword()).isEmpty()) {
            // Check if new passwords are same
            if (Arrays.equals(txtNewPassword.getPassword(), txtConfirmNewPassword.getPassword())) {
                // Check if password is verified
                if (tutor.verify(Main.cryptography, String.valueOf(txtOldPassword.getPassword()))) {
                    // Create a confirmation message box
                    int confirmationResult = JOptionPane.showConfirmDialog(null,
                        "Do you want to proceed?",
                        "Update Password",
                        JOptionPane.YES_NO_OPTION);

                    // Result of the confirmation message box
                    if (confirmationResult == 0) {
                        // Get index of current tutor
                        int index = Main.tutorDatabase.getIndex(tutor);
        
                        // Set updated tutor password
                        tutor.setPassword(String.valueOf(txtNewPassword.getPassword()), Main.cryptography);
        
                        // Update data in SecureDatabase
                        Main.tutorDatabase.updateData(index, tutor);
        
                        // Display success message
                        JOptionPane.showMessageDialog(new JFrame(), "Password Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        
                        // Refresh the page
                        frame.navigateContentPanel(new TutorChangePasswordPnl(frame, tutor));
                    }
                } else {
                    // Display error message
                    JOptionPane.showMessageDialog(new JFrame(), "Incorrect Password", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Display error message
                JOptionPane.showMessageDialog(new JFrame(), "New Password Is Different", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Display error message
            JOptionPane.showMessageDialog(new JFrame(), "Password Cannot Be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfirmNewPassword;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JPanel pnlUpdatePassword;
    private javax.swing.JPasswordField txtConfirmNewPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
