package gui.hq.attendance;

import gui.HQPanelContainer;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import tutormanagementsystem.Attendance;
import tutormanagementsystem.Branch;
import tutormanagementsystem.Main;
import tutormanagementsystem.Tutor;

public class HQAddAttendancePnl extends javax.swing.JPanel {
    private HQPanelContainer frame;
    private Branch branch;

    public HQAddAttendancePnl(HQPanelContainer frame, Branch branch) {
        initComponents();
        this.frame = frame;
        this.branch = branch;

        populateCmbTutorId();

        // Populate text fields
        txtBranchName.setText(branch.getName());
        txtDate.setText(LocalDateTime.now().format(Main.DATE_FORMATTER));
    }

    // Populate combobox data
    private void populateCmbTutorId() {
        // Remove existing combobox items
        cmbTutorId.removeAllItems();

        // Get tutor id from branch
        for (int i = 0; i < Main.tutorDatabase.getSize(); i++) {
            Tutor tutor = Main.tutorDatabase.getData(i);
            if (tutor.getBranchId() == branch.getId()) {
                cmbTutorId.addItem(String.format("%.0f", tutor.getId()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlAddAttendanceContainer = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        pnlAttendanceDetails = new javax.swing.JPanel();
        lblBranchName = new javax.swing.JLabel();
        lblTutorId = new javax.swing.JLabel();
        lblTutorName = new javax.swing.JLabel();
        lblAttendedHours = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtBranchName = new javax.swing.JTextField();
        cmbTutorId = new javax.swing.JComboBox<>();
        txtTutorName = new javax.swing.JTextField();
        txtAttendedHours = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlAddAttendanceContainer.setBackground(new java.awt.Color(242, 242, 242));
        pnlAddAttendanceContainer.setMinimumSize(new java.awt.Dimension(500, 450));

        btnAdd.setBackground(new java.awt.Color(0, 0, 43));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        pnlAttendanceDetails.setBackground(new java.awt.Color(230, 230, 230));

        lblBranchName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBranchName.setText("Branch");

        lblTutorId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTutorId.setText("Tutor ID");

        lblTutorName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTutorName.setText("Tutor Name");

        lblAttendedHours.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAttendedHours.setText("Attended Hours");

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDate.setText("Date");

        txtBranchName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBranchName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBranchName.setEnabled(false);

        cmbTutorId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbTutorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTutorIdActionPerformed(evt);
            }
        });

        txtTutorName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTutorName.setEnabled(false);

        txtAttendedHours.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtAttendedHours.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAttendedHours.setMaximumSize(new java.awt.Dimension(190, 26));
        txtAttendedHours.setMinimumSize(new java.awt.Dimension(190, 26));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDate.setEnabled(false);

        javax.swing.GroupLayout pnlAttendanceDetailsLayout = new javax.swing.GroupLayout(pnlAttendanceDetails);
        pnlAttendanceDetails.setLayout(pnlAttendanceDetailsLayout);
        pnlAttendanceDetailsLayout.setHorizontalGroup(
            pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranchName)
                    .addComponent(lblTutorId)
                    .addComponent(lblTutorName)
                    .addComponent(lblAttendedHours)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAttendedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate)
                    .addComponent(txtTutorName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbTutorId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        pnlAttendanceDetailsLayout.setVerticalGroup(
            pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchName))
                .addGap(28, 28, 28)
                .addGroup(pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTutorId)
                    .addComponent(cmbTutorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTutorName)
                    .addComponent(txtTutorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttendedHours)
                    .addComponent(txtAttendedHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlAttendanceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnlAddAttendanceContainerLayout = new javax.swing.GroupLayout(pnlAddAttendanceContainer);
        pnlAddAttendanceContainer.setLayout(pnlAddAttendanceContainerLayout);
        pnlAddAttendanceContainerLayout.setHorizontalGroup(
            pnlAddAttendanceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddAttendanceContainerLayout.createSequentialGroup()
                .addGroup(pnlAddAttendanceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddAttendanceContainerLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddAttendanceContainerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pnlAttendanceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlAddAttendanceContainerLayout.setVerticalGroup(
            pnlAddAttendanceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddAttendanceContainerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pnlAttendanceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAdd)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pnlAddAttendanceContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAddAttendanceContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!txtAttendedHours.getText().isEmpty() && !cmbTutorId.getSelectedItem().toString().isEmpty()) {
            // Save attendance data
            Attendance attendance = new Attendance(Main.attendanceBlockchain.generateId(), Double.parseDouble(txtAttendedHours.getText()), LocalDateTime.now(), Double.parseDouble(cmbTutorId.getSelectedItem().toString()));
            Main.attendanceBlockchain.add(attendance);

            // Display success message
            JOptionPane.showMessageDialog(new JFrame(), "Attendance Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Refresh the page
            frame.navigateContentPanel(new HQAddAttendancePnl(frame, branch));
        } else {
            // Display error message
            JOptionPane.showMessageDialog(new JFrame(), "Fields Cannot Be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbTutorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTutorIdActionPerformed
        // Update tutor fields
        txtTutorName.setText(Main.tutorDatabase.findData(Double.parseDouble(cmbTutorId.getSelectedItem().toString())).getName());
    }//GEN-LAST:event_cmbTutorIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cmbTutorId;
    private javax.swing.JLabel lblAttendedHours;
    private javax.swing.JLabel lblBranchName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTutorId;
    private javax.swing.JLabel lblTutorName;
    private javax.swing.JPanel pnlAddAttendanceContainer;
    private javax.swing.JPanel pnlAttendanceDetails;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JTextField txtAttendedHours;
    private javax.swing.JTextField txtBranchName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtTutorName;
    // End of variables declaration//GEN-END:variables
}
