package gui.hq.attendance;

import gui.HQPanelContainer;

import java.awt.Color;

import tutormanagementsystem.Branch;

public class HQAttendanceRightMenu extends javax.swing.JPanel {
    private HQPanelContainer frame;
    private Branch branch;

    public HQAttendanceRightMenu(HQPanelContainer frame, Branch branch) {
        initComponents();
        this.frame = frame;
        this.branch = branch;

        frame.navigateContentPanel(new HQAddAttendancePnl(frame, branch));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        pnlRightMenu = new javax.swing.JPanel();
        pnlAddAttendance = new javax.swing.JPanel();
        lblAddAttendance = new javax.swing.JLabel();
        pnlAttendanceRecord = new javax.swing.JPanel();
        lblAttendanceRecord = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        pnlRightBg.setLayout(new java.awt.BorderLayout());
        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 590, 550));

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlAddAttendance.setBackground(new java.awt.Color(63, 91, 135));
        pnlAddAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddAttendanceMouseClicked(evt);
            }
        });

        lblAddAttendance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddAttendance.setForeground(new java.awt.Color(255, 255, 255));
        lblAddAttendance.setText("Add Attendance");

        javax.swing.GroupLayout pnlAddAttendanceLayout = new javax.swing.GroupLayout(pnlAddAttendance);
        pnlAddAttendance.setLayout(pnlAddAttendanceLayout);
        pnlAddAttendanceLayout.setHorizontalGroup(
            pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblAddAttendance)
                .addGap(55, 55, 55))
        );
        pnlAddAttendanceLayout.setVerticalGroup(
            pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAddAttendance)
                .addGap(17, 17, 17))
        );

        pnlAttendanceRecord.setBackground(new java.awt.Color(39, 56, 83));
        pnlAttendanceRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAttendanceRecordMouseClicked(evt);
            }
        });

        lblAttendanceRecord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAttendanceRecord.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendanceRecord.setText("Attendance Record");

        javax.swing.GroupLayout pnlAttendanceRecordLayout = new javax.swing.GroupLayout(pnlAttendanceRecord);
        pnlAttendanceRecord.setLayout(pnlAttendanceRecordLayout);
        pnlAttendanceRecordLayout.setHorizontalGroup(
            pnlAttendanceRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAttendanceRecordLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblAttendanceRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAttendanceRecordLayout.setVerticalGroup(
            pnlAttendanceRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceRecordLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAttendanceRecord)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGroup(pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAddAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAttendanceRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(pnlAddAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlAttendanceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddAttendanceMouseClicked
        pnlAddAttendance.setBackground(new Color(63,91,135));
        pnlAttendanceRecord.setBackground(new Color(39,56,83));
        
        frame.navigateContentPanel(new HQAddAttendancePnl(frame, branch));
    }//GEN-LAST:event_pnlAddAttendanceMouseClicked

    private void pnlAttendanceRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAttendanceRecordMouseClicked
        pnlAttendanceRecord.setBackground(new Color(63,91,135));
        pnlAddAttendance.setBackground(new Color(39,56,83));
        
        frame.navigateContentPanel(new HQSearchAttendancePnl());
    }//GEN-LAST:event_pnlAttendanceRecordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddAttendance;
    private javax.swing.JLabel lblAttendanceRecord;
    private javax.swing.JPanel pnlAddAttendance;
    private javax.swing.JPanel pnlAttendanceRecord;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JPanel pnlRightMenu;
    // End of variables declaration//GEN-END:variables
}
