package gui;

import gui.tcentre.attendance.TCentreAttendanceRightMenu;
import gui.tcentre.tutor.TCentreTutorRightMenu;
import java.awt.Color;
import javax.swing.JPanel;
import tutormanagementsystem.Branch;

public class TCentrePanelContainer extends javax.swing.JFrame {
    //Variable for GUI draggable
    private int mousepX, mousepY;
    private Branch branch;

    public TCentrePanelContainer(Branch branch) {
        initComponents();
        this.branch = branch;
        
        navigateMenuPanel(new TCentreTutorRightMenu(this, branch));
    }

    //Change panels
    public void navigateMenuPanel(JPanel panel){
        //remove all previous content
        pnlRightMenu.removeAll();
        //add the new panel
        pnlRightMenu.add(panel);
        pnlRightMenu.revalidate();
    }

    public void navigateContentPanel(JPanel panel){
        //remove all previous content
        pnlRightContent.removeAll();
        //add the new panel
        pnlRightContent.add(panel);
        pnlRightContent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeftMenu = new javax.swing.JPanel();
        pnlTutor = new javax.swing.JPanel();
        lblTutor = new javax.swing.JLabel();
        lblVerticalBar1 = new javax.swing.JLabel();
        pnlAttendance = new javax.swing.JPanel();
        lblAttendance = new javax.swing.JLabel();
        lblVerticalBar2 = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        pnlRightContainer = new javax.swing.JPanel();
        pnlRightMenu = new javax.swing.JPanel();
        pnlRightContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 550));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnlLeftMenu.setBackground(new java.awt.Color(24, 34, 56));
        pnlLeftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTutor.setBackground(new java.awt.Color(39, 56, 83));
        pnlTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTutorMouseClicked(evt);
            }
        });

        lblTutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTutor.setForeground(new java.awt.Color(255, 255, 255));
        lblTutor.setText("Tutor");

        lblVerticalBar1.setBackground(new java.awt.Color(255, 255, 255));
        lblVerticalBar1.setForeground(new java.awt.Color(255, 255, 255));
        lblVerticalBar1.setOpaque(true);

        javax.swing.GroupLayout pnlTutorLayout = new javax.swing.GroupLayout(pnlTutor);
        pnlTutor.setLayout(pnlTutorLayout);
        pnlTutorLayout.setHorizontalGroup(
            pnlTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTutorLayout.createSequentialGroup()
                .addComponent(lblVerticalBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblTutor)
                .addGap(55, 55, 55))
        );
        pnlTutorLayout.setVerticalGroup(
            pnlTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTutorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTutor)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(lblVerticalBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlLeftMenu.add(pnlTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, -1));

        pnlAttendance.setBackground(new java.awt.Color(24, 34, 56));
        pnlAttendance.setForeground(new java.awt.Color(255, 255, 255));
        pnlAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAttendanceMouseClicked(evt);
            }
        });

        lblAttendance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAttendance.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendance.setText("Attendance");

        lblVerticalBar2.setBackground(new java.awt.Color(24, 34, 56));
        lblVerticalBar2.setForeground(new java.awt.Color(255, 255, 255));
        lblVerticalBar2.setOpaque(true);

        javax.swing.GroupLayout pnlAttendanceLayout = new javax.swing.GroupLayout(pnlAttendance);
        pnlAttendance.setLayout(pnlAttendanceLayout);
        pnlAttendanceLayout.setHorizontalGroup(
            pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAttendanceLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAttendance)
                .addGap(47, 47, 47))
            .addGroup(pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAttendanceLayout.createSequentialGroup()
                    .addComponent(lblVerticalBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 160, Short.MAX_VALUE)))
        );
        pnlAttendanceLayout.setVerticalGroup(
            pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAttendance)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblVerticalBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        pnlLeftMenu.add(pnlAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        pnlLogout.setBackground(new java.awt.Color(24, 34, 56));
        pnlLogout.setForeground(new java.awt.Color(255, 255, 255));
        pnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Log out");

        javax.swing.GroupLayout pnlLogoutLayout = new javax.swing.GroupLayout(pnlLogout);
        pnlLogout.setLayout(pnlLogoutLayout);
        pnlLogoutLayout.setHorizontalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoutLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblLogout)
                .addGap(47, 47, 47))
        );
        pnlLogoutLayout.setVerticalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogout)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlLeftMenu.add(pnlLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, 50));

        pnlRightMenu.setLayout(new java.awt.BorderLayout());

        pnlRightContent.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlRightContainerLayout = new javax.swing.GroupLayout(pnlRightContainer);
        pnlRightContainer.setLayout(pnlRightContainerLayout);
        pnlRightContainerLayout.setHorizontalGroup(
            pnlRightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightContainerLayout.createSequentialGroup()
                .addComponent(pnlRightMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlRightContent, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlRightContainerLayout.setVerticalGroup(
            pnlRightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRightMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRightContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlLeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlRightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlLeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // Draggable - get X and Y 
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //Draggable
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        this.setLocation(coordinateX-mousepX,coordinateY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void pnlAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAttendanceMouseClicked
        pnlAttendance.setBackground(new Color(39,56,83));
        lblVerticalBar2.setBackground(new Color(255,255,255));

        pnlTutor.setBackground(new Color(24,34,56));
        lblVerticalBar1.setBackground(new Color(24,34,56));

        navigateMenuPanel(new TCentreAttendanceRightMenu(this, branch));
    }//GEN-LAST:event_pnlAttendanceMouseClicked

    private void pnlTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTutorMouseClicked
        pnlTutor.setBackground(new Color(39,56,83));
        lblVerticalBar1.setBackground(new Color(255,255,255));

        pnlAttendance.setBackground(new Color(24,34,56));
        lblVerticalBar2.setBackground(new Color(24,34,56));

        navigateMenuPanel(new TCentreTutorRightMenu(this, branch));
    }//GEN-LAST:event_pnlTutorMouseClicked

    private void pnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseClicked
        //Logout and show the login form
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlLogoutMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAttendance;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblTutor;
    private javax.swing.JLabel lblVerticalBar1;
    private javax.swing.JLabel lblVerticalBar2;
    private javax.swing.JPanel pnlAttendance;
    private javax.swing.JPanel pnlLeftMenu;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlRightContainer;
    private javax.swing.JPanel pnlRightContent;
    private javax.swing.JPanel pnlRightMenu;
    private javax.swing.JPanel pnlTutor;
    // End of variables declaration//GEN-END:variables
}
