package gui;

import gui.tutor.profile.TutorProfileRightMenu;
import gui.tutor.payment.TutorPaymentRightMenu;
import java.awt.Color;
import javax.swing.JPanel;
import tutormanagementsystem.Tutor;

public class TutorPanelContainer extends javax.swing.JFrame {
    //Variable for GUI draggable
    private int mousepX, mousepY;
    private Tutor tutor;

    public TutorPanelContainer(Tutor tutor) {
        initComponents();
        this.tutor = tutor;

        navigateMenuPanel(new TutorProfileRightMenu(this, tutor));
    }

    //Change panels
    public void navigateMenuPanel(JPanel panel){
        //remove all previous content
        pnlRightMenu.removeAll();
        //add the new panel
        pnlRightMenu.add(panel);
        pnlRightMenu.revalidate();
    }

    public void navigateContentPanel(JPanel panel){
        //remove all previous content
        pnlRightContent.removeAll();
        //add the new panel
        pnlRightContent.add(panel);
        pnlRightContent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeftMenu = new javax.swing.JPanel();
        pnlProfile = new javax.swing.JPanel();
        lblTutor = new javax.swing.JLabel();
        lblVerticalBar1 = new javax.swing.JLabel();
        pnlPayment = new javax.swing.JPanel();
        lblAttendance = new javax.swing.JLabel();
        lblVerticalBar2 = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        pnlRightContainer = new javax.swing.JPanel();
        pnlRightMenu = new javax.swing.JPanel();
        pnlRightContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 550));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnlLeftMenu.setBackground(new java.awt.Color(24, 34, 56));
        pnlLeftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProfile.setBackground(new java.awt.Color(39, 56, 83));
        pnlProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProfileMouseClicked(evt);
            }
        });

        lblTutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTutor.setForeground(new java.awt.Color(255, 255, 255));
        lblTutor.setText("Profile");

        lblVerticalBar1.setBackground(new java.awt.Color(255, 255, 255));
        lblVerticalBar1.setForeground(new java.awt.Color(255, 255, 255));
        lblVerticalBar1.setOpaque(true);

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileLayout.createSequentialGroup()
                .addComponent(lblVerticalBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblTutor)
                .addGap(55, 55, 55))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTutor)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(lblVerticalBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlLeftMenu.add(pnlProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, -1));

        pnlPayment.setBackground(new java.awt.Color(24, 34, 56));
        pnlPayment.setForeground(new java.awt.Color(255, 255, 255));
        pnlPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPaymentMouseClicked(evt);
            }
        });

        lblAttendance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAttendance.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendance.setText("Payment");

        lblVerticalBar2.setBackground(new java.awt.Color(24, 34, 56));
        lblVerticalBar2.setForeground(new java.awt.Color(255, 255, 255));
        lblVerticalBar2.setOpaque(true);

        javax.swing.GroupLayout pnlPaymentLayout = new javax.swing.GroupLayout(pnlPayment);
        pnlPayment.setLayout(pnlPaymentLayout);
        pnlPaymentLayout.setHorizontalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAttendance)
                .addGap(47, 47, 47))
            .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPaymentLayout.createSequentialGroup()
                    .addComponent(lblVerticalBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 145, Short.MAX_VALUE)))
        );
        pnlPaymentLayout.setVerticalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAttendance)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblVerticalBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        pnlLeftMenu.add(pnlPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        pnlLogout.setBackground(new java.awt.Color(24, 34, 56));
        pnlLogout.setForeground(new java.awt.Color(255, 255, 255));
        pnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Log out");

        javax.swing.GroupLayout pnlLogoutLayout = new javax.swing.GroupLayout(pnlLogout);
        pnlLogout.setLayout(pnlLogoutLayout);
        pnlLogoutLayout.setHorizontalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoutLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblLogout)
                .addGap(47, 47, 47))
        );
        pnlLogoutLayout.setVerticalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogout)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlLeftMenu.add(pnlLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, 50));

        pnlRightMenu.setLayout(new java.awt.BorderLayout());

        pnlRightContent.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlRightContainerLayout = new javax.swing.GroupLayout(pnlRightContainer);
        pnlRightContainer.setLayout(pnlRightContainerLayout);
        pnlRightContainerLayout.setHorizontalGroup(
            pnlRightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightContainerLayout.createSequentialGroup()
                .addComponent(pnlRightMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlRightContent, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlRightContainerLayout.setVerticalGroup(
            pnlRightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRightMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRightContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlLeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlRightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlLeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // Draggable - get X and Y 
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //Draggable
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        this.setLocation(coordinateX-mousepX,coordinateY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void pnlPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaymentMouseClicked
        pnlPayment.setBackground(new Color(39,56,83));
        lblVerticalBar2.setBackground(new Color(255,255,255));

        pnlProfile.setBackground(new Color(24,34,56));
        lblVerticalBar1.setBackground(new Color(24,34,56));

        navigateMenuPanel(new TutorPaymentRightMenu(this, tutor));
    }//GEN-LAST:event_pnlPaymentMouseClicked

    private void pnlProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProfileMouseClicked
        pnlProfile.setBackground(new Color(39,56,83));
        lblVerticalBar1.setBackground(new Color(255,255,255));

        pnlPayment.setBackground(new Color(24,34,56));
        lblVerticalBar2.setBackground(new Color(24,34,56));

        navigateMenuPanel(new TutorProfileRightMenu(this, tutor));
    }//GEN-LAST:event_pnlProfileMouseClicked

    private void pnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseClicked
        //Logout and show the login form
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlLogoutMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAttendance;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblTutor;
    private javax.swing.JLabel lblVerticalBar1;
    private javax.swing.JLabel lblVerticalBar2;
    private javax.swing.JPanel pnlLeftMenu;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlRightContainer;
    private javax.swing.JPanel pnlRightContent;
    private javax.swing.JPanel pnlRightMenu;
    // End of variables declaration//GEN-END:variables
}
