package gui.tutor.payment;

import gui.TutorPanelContainer;
import tutormanagementsystem.Tutor;

public class TutorPaymentRightMenuSecondVer extends javax.swing.JPanel {
    private TutorPanelContainer frame;
    private Tutor tutor;

    public TutorPaymentRightMenuSecondVer(TutorPanelContainer frame, Tutor tutor) {
        initComponents();
        this.frame = frame;
        this.tutor = tutor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightMenu = new javax.swing.JPanel();
        pnlSearchTutor = new javax.swing.JPanel();
        lblBackToSearch = new javax.swing.JLabel();
        lblIconBack = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlSearchTutor.setBackground(new java.awt.Color(63, 91, 135));
        pnlSearchTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSearchTutorMouseClicked(evt);
            }
        });

        lblBackToSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBackToSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblBackToSearch.setText("Back to Search");

        lblIconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/icon_back.png"))); // NOI18N

        javax.swing.GroupLayout pnlSearchTutorLayout = new javax.swing.GroupLayout(pnlSearchTutor);
        pnlSearchTutor.setLayout(pnlSearchTutorLayout);
        pnlSearchTutorLayout.setHorizontalGroup(
            pnlSearchTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchTutorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblIconBack)
                .addGap(14, 14, 14)
                .addComponent(lblBackToSearch)
                .addGap(58, 58, 58))
        );
        pnlSearchTutorLayout.setVerticalGroup(
            pnlSearchTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTutorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlSearchTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBackToSearch)
                    .addComponent(lblIconBack))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSearchTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(pnlSearchTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlSearchTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSearchTutorMouseClicked
        frame.navigateContentPanel(new TutorPaymentPnlLatest(frame, tutor));
        frame.navigateMenuPanel(new TutorPaymentRightMenu(frame, tutor));
    }//GEN-LAST:event_pnlSearchTutorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackToSearch;
    private javax.swing.JLabel lblIconBack;
    private javax.swing.JPanel pnlRightMenu;
    private javax.swing.JPanel pnlSearchTutor;
    // End of variables declaration//GEN-END:variables
}
