package gui.tutor.payment;

import gui.TutorPanelContainer;
import tutormanagementsystem.Tutor;

public class TutorPaymentRightMenu extends javax.swing.JPanel {

    public TutorPaymentRightMenu(TutorPanelContainer frame, Tutor tutor) {
        initComponents();

        frame.navigateContentPanel(new TutorPaymentPnlLatest(frame, tutor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightMenu = new javax.swing.JPanel();
        pnlSearchTutor = new javax.swing.JPanel();
        lblBackToSearchTutor = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlSearchTutor.setBackground(new java.awt.Color(63, 91, 135));

        lblBackToSearchTutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBackToSearchTutor.setForeground(new java.awt.Color(255, 255, 255));
        lblBackToSearchTutor.setText("Payment Record");

        javax.swing.GroupLayout pnlSearchTutorLayout = new javax.swing.GroupLayout(pnlSearchTutor);
        pnlSearchTutor.setLayout(pnlSearchTutorLayout);
        pnlSearchTutorLayout.setHorizontalGroup(
            pnlSearchTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchTutorLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblBackToSearchTutor)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlSearchTutorLayout.setVerticalGroup(
            pnlSearchTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTutorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBackToSearchTutor)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSearchTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(pnlSearchTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackToSearchTutor;
    private javax.swing.JPanel pnlRightMenu;
    private javax.swing.JPanel pnlSearchTutor;
    // End of variables declaration//GEN-END:variables
}
