package gui.hq.tcentre;

import gui.HQPanelContainer;
import tutormanagementsystem.Branch;
import tutormanagementsystem.BranchCategory;
import tutormanagementsystem.Main;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class HQAddTCentrePnl extends javax.swing.JPanel {
    private HQPanelContainer frame;

    public HQAddTCentrePnl(HQPanelContainer frame) {
        initComponents();
        this.frame = frame;

        // Populate text fields
        txtBranchId.setText(String.format("%.0f", Main.branchDatabase.generateId()));
        txtCategory.setText(BranchCategory.BRANCH.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlAddTCentreContainer = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        pnlBranchDetails = new javax.swing.JPanel();
        lblBranchID = new javax.swing.JLabel();
        lblBranchName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtBranchId = new javax.swing.JTextField();
        txtBranchName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlAddTCentreContainer.setBackground(new java.awt.Color(242, 242, 242));
        pnlAddTCentreContainer.setMinimumSize(new java.awt.Dimension(500, 450));

        btnAdd.setBackground(new java.awt.Color(0, 0, 43));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        pnlBranchDetails.setBackground(new java.awt.Color(230, 230, 230));

        lblBranchID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBranchID.setText("ID");

        lblBranchName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBranchName.setText("Name");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAddress.setText("Address");

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCategory.setText("Category");

        txtBranchId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBranchId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBranchId.setEnabled(false);

        txtBranchName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPhoneNumber.setMaximumSize(new java.awt.Dimension(190, 26));
        txtPhoneNumber.setMinimumSize(new java.awt.Dimension(190, 26));

        txtCategory.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCategory.setEnabled(false);

        javax.swing.GroupLayout pnlBranchDetailsLayout = new javax.swing.GroupLayout(pnlBranchDetails);
        pnlBranchDetails.setLayout(pnlBranchDetailsLayout);
        pnlBranchDetailsLayout.setHorizontalGroup(
            pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBranchDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranchID)
                    .addComponent(lblBranchName)
                    .addComponent(lblAddress)
                    .addComponent(lblPhoneNumber)
                    .addComponent(lblCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtBranchName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtBranchId, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(33, 33, 33))
        );
        pnlBranchDetailsLayout.setVerticalGroup(
            pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBranchDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchID))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranchName)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnlAddTCentreContainerLayout = new javax.swing.GroupLayout(pnlAddTCentreContainer);
        pnlAddTCentreContainer.setLayout(pnlAddTCentreContainerLayout);
        pnlAddTCentreContainerLayout.setHorizontalGroup(
            pnlAddTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddTCentreContainerLayout.createSequentialGroup()
                .addGroup(pnlAddTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddTCentreContainerLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddTCentreContainerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pnlBranchDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        pnlAddTCentreContainerLayout.setVerticalGroup(
            pnlAddTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddTCentreContainerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pnlBranchDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnAdd)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(pnlAddTCentreContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(18, 18, 18)
                .addComponent(pnlAddTCentreContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!txtBranchId.getText().isEmpty() && !txtBranchName.getText().isEmpty() && !txtAddress.getText().isEmpty() && !txtPhoneNumber.getText().isEmpty()) {
            // Save branch data
            Branch branch = new Branch(Double.parseDouble(txtBranchId.getText()), txtBranchName.getText(), txtAddress.getText(), txtPhoneNumber.getText(), "", BranchCategory.BRANCH);
            // Set default password
            branch.setPassword(Main.DEFAULT_PASSWORD, Main.cryptography);
            Main.branchDatabase.add(branch);

            // Display success message
            JOptionPane.showMessageDialog(new JFrame(), "Branch Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Refresh the page
            frame.navigateContentPanel(new HQAddTCentrePnl(frame));
        } else {
            // Display error message
            JOptionPane.showMessageDialog(new JFrame(), "Fields Cannot Be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBranchID;
    private javax.swing.JLabel lblBranchName;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JPanel pnlAddTCentreContainer;
    private javax.swing.JPanel pnlBranchDetails;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBranchId;
    private javax.swing.JTextField txtBranchName;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
