package gui.hq.tcentre;

import gui.HQPanelContainer;
import tutormanagementsystem.Branch;
import tutormanagementsystem.Main;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class HQEditTCentrePnl extends javax.swing.JPanel {
    private HQPanelContainer frame;
    private Branch branch;

    public HQEditTCentrePnl(HQPanelContainer frame, Branch branch) {
        initComponents();
        this.frame = frame;
        this.branch = branch;

        // Populate text fields
        txtBranchID.setText(String.format("%.0f", branch.getId()));
        txtName.setText(branch.getName());
        txtAddress.setText(branch.getAddress());
        txtPhoneNumber.setText(branch.getPhoneNumber());
        txtCategory.setText(branch.getCategory().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlUpdateBranchContainer = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        pnlBranchDetails = new javax.swing.JPanel();
        lblBranchID = new javax.swing.JLabel();
        lblBranchName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtBranchID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlUpdateBranchContainer.setBackground(new java.awt.Color(242, 242, 242));
        pnlUpdateBranchContainer.setMinimumSize(new java.awt.Dimension(500, 450));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 43));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        pnlBranchDetails.setBackground(new java.awt.Color(230, 230, 230));

        lblBranchID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBranchID.setText("ID");

        lblBranchName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBranchName.setText("Name");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAddress.setText("Address");

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCategory.setText("Category");

        txtBranchID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBranchID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBranchID.setEnabled(false);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPhoneNumber.setMaximumSize(new java.awt.Dimension(190, 26));
        txtPhoneNumber.setMinimumSize(new java.awt.Dimension(190, 26));

        txtCategory.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCategory.setEnabled(false);

        javax.swing.GroupLayout pnlBranchDetailsLayout = new javax.swing.GroupLayout(pnlBranchDetails);
        pnlBranchDetails.setLayout(pnlBranchDetailsLayout);
        pnlBranchDetailsLayout.setHorizontalGroup(
            pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBranchDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranchID)
                    .addComponent(lblBranchName)
                    .addComponent(lblAddress)
                    .addComponent(lblPhoneNumber)
                    .addComponent(lblCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtBranchID, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(33, 33, 33))
        );
        pnlBranchDetailsLayout.setVerticalGroup(
            pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBranchDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchID))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranchName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnlUpdateBranchContainerLayout = new javax.swing.GroupLayout(pnlUpdateBranchContainer);
        pnlUpdateBranchContainer.setLayout(pnlUpdateBranchContainerLayout);
        pnlUpdateBranchContainerLayout.setHorizontalGroup(
            pnlUpdateBranchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateBranchContainerLayout.createSequentialGroup()
                .addGroup(pnlUpdateBranchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateBranchContainerLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdateBranchContainerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pnlBranchDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        pnlUpdateBranchContainerLayout.setVerticalGroup(
            pnlUpdateBranchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateBranchContainerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pnlBranchDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnUpdate)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRightBgLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(pnlUpdateBranchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(523, 523, 523))
            .addGroup(pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRightBgLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(pnlUpdateBranchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!txtName.getText().isEmpty() && !txtAddress.getText().isEmpty() && !txtPhoneNumber.getText().isEmpty()) {
            // Set updated branch data
            branch.setName(txtName.getText());
            branch.setAddress(txtAddress.getText());
            branch.setPhoneNumber(txtPhoneNumber.getText());

            // Save database
            Main.branchDatabase.save();

            // Display success message
            JOptionPane.showMessageDialog(new JFrame(), "Branch Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Refresh the page
            frame.navigateMenuPanel(new HQTCentreRightMenu(frame, 1));
        } else {
            // Display error message
            JOptionPane.showMessageDialog(new JFrame(), "Fields Cannot Be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBranchID;
    private javax.swing.JLabel lblBranchName;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JPanel pnlBranchDetails;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JPanel pnlUpdateBranchContainer;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBranchID;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
