package gui.hq.tcentre;

import gui.HQPanelContainer;
import tutormanagementsystem.Branch;
import tutormanagementsystem.Main;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class HQSearchTCentrePnl extends javax.swing.JPanel {
    private HQPanelContainer frame;

    public HQSearchTCentrePnl(HQPanelContainer frame) {
        initComponents();
        this.frame = frame;

        populateTblBranch();
    }

    // Populate table data
    private void populateTblBranch() {
        // Get table model
        DefaultTableModel model = (DefaultTableModel) tblBranch.getModel();
        // Remove existing table data
        model.setRowCount(0);

        for (int i = 0; i < Main.branchDatabase.getSize(); i++) {
            Branch branch = Main.branchDatabase.getData(i);
            model.addRow(new Object[] {String.format("%.0f", branch.getId()), branch.getName(), branch.getPhoneNumber(), branch.getAddress()});
        }
    }

    // Filter data
    private void filter(String query) {
        // Get table model and create sorter
        DefaultTableModel model = (DefaultTableModel) tblBranch.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblBranch.setRowSorter(sorter);

        // Filter the data
        if (query.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlSearchTCentreContainer = new javax.swing.JPanel();
        scrpnlBranchTable = new javax.swing.JScrollPane();
        tblBranch = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnTerminate = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlSearchTCentreContainer.setBackground(new java.awt.Color(242, 242, 242));
        pnlSearchTCentreContainer.setMinimumSize(new java.awt.Dimension(500, 450));

        scrpnlBranchTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrpnlBranchTable.setPreferredSize(new java.awt.Dimension(452, 200));

        tblBranch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone Number", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBranch.setPreferredSize(null);
        tblBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBranchMouseClicked(evt);
            }
        });
        scrpnlBranchTable.setViewportView(tblBranch);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 0, 43));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("Select a tutor and press this.");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTerminate.setBackground(new java.awt.Color(0, 0, 43));
        btnTerminate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTerminate.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminate.setText("Terminate");
        btnTerminate.setToolTipText("Select a tutor and press this.");
        btnTerminate.setEnabled(false);
        btnTerminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminateActionPerformed(evt);
            }
        });

        btnChangePassword.setBackground(new java.awt.Color(0, 0, 43));
        btnChangePassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("Change Password");
        btnChangePassword.setToolTipText("Select a tutor and press this.");
        btnChangePassword.setEnabled(false);
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchTCentreContainerLayout = new javax.swing.GroupLayout(pnlSearchTCentreContainer);
        pnlSearchTCentreContainer.setLayout(pnlSearchTCentreContainerLayout);
        pnlSearchTCentreContainerLayout.setHorizontalGroup(
            pnlSearchTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTCentreContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSearchTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrpnlBranchTable, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSearchTCentreContainerLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSearchTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlSearchTCentreContainerLayout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnTerminate))
                            .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        pnlSearchTCentreContainerLayout.setVerticalGroup(
            pnlSearchTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTCentreContainerLayout.createSequentialGroup()
                .addGroup(pnlSearchTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchTCentreContainerLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnlSearchTCentreContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTerminate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSearchTCentreContainerLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(scrpnlBranchTable, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRightBgLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(pnlSearchTCentreContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(523, 523, 523))
            .addGroup(pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRightBgLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(pnlSearchTCentreContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void tblBranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBranchMouseClicked
        // Enable edit, terminate, and change password button
        btnEdit.setEnabled(true);
        btnTerminate.setEnabled(true);
        btnChangePassword.setEnabled(true);
    }//GEN-LAST:event_tblBranchMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // Get the input and call filter()
        String query = txtSearch.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Get model of the table, then get selected row
        DefaultTableModel model = (DefaultTableModel) tblBranch.getModel();
        int selectedRowIndex = tblBranch.convertRowIndexToModel(tblBranch.getSelectedRow());

        // Get the tutorID
        double id = Double.parseDouble(model.getValueAt(selectedRowIndex, 0).toString());

        frame.navigateMenuPanel(new HQTCentreRightMenuSecondVer(frame));
        frame.navigateContentPanel(new HQEditTCentrePnl(frame, Main.branchDatabase.findData(id)));
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTerminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminateActionPerformed
        // Get model of the table, then get selected row
        DefaultTableModel model = (DefaultTableModel) tblBranch.getModel();
        int selectedRowIndex = tblBranch.convertRowIndexToModel(tblBranch.getSelectedRow());

        // Get the branchId
        double id = Double.parseDouble(model.getValueAt(selectedRowIndex, 0).toString());

        // Check if there is existing tutors
        boolean existingTutors = false;
        for (int i = 0; i < Main.tutorDatabase.getSize(); i++) {
            if (Main.tutorDatabase.getData(i).getBranchId() == id) {
                existingTutors = true;
                break;
            }
        }

        if (!existingTutors) {
            int confirmationResult = JOptionPane.showConfirmDialog(null,
                "Do you want to terminate this account?",
                "Terminate Tuition Centre",
                JOptionPane.YES_NO_OPTION);

            // Result of the confirmation message box
            if (confirmationResult == 0) {
                // Remove data from database
                Main.branchDatabase.removeData(id);

                // Display success message
                JOptionPane.showMessageDialog(new JFrame(), "Tutor Terminated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

                // Refresh the page
                frame.navigateContentPanel(new HQSearchTCentrePnl(frame));
            }
        } else {
            // Display error message
            JOptionPane.showMessageDialog(new JFrame(), "There Are Existing Tutors", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTerminateActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // Get model of the table, then get selected row
        DefaultTableModel model = (DefaultTableModel) tblBranch.getModel();
        int selectedRowIndex = tblBranch.convertRowIndexToModel(tblBranch.getSelectedRow());

        // Get the tutorID
        double id = Double.parseDouble(model.getValueAt(selectedRowIndex, 0).toString());

        HQTCentreRightMenuSecondVer rightMenuSecondVer = new HQTCentreRightMenuSecondVer(frame);
        frame.navigateMenuPanel(rightMenuSecondVer);

        HQTCentreChangePassPnl changePassPnl = new HQTCentreChangePassPnl(frame, Main.branchDatabase.findData(id));
        frame.navigateContentPanel(changePassPnl);
    }//GEN-LAST:event_btnChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnTerminate;
    private javax.swing.JLabel lblClose;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JPanel pnlSearchTCentreContainer;
    private javax.swing.JScrollPane scrpnlBranchTable;
    private javax.swing.JTable tblBranch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
