package gui.hq.tcentre;

import gui.HQPanelContainer;
import java.awt.Color;

public class HQTCentreRightMenu extends javax.swing.JPanel {
    private HQPanelContainer frame;

    public HQTCentreRightMenu(HQPanelContainer frame) {
        initComponents();
        this.frame = frame;

        HQAddTCentrePnl addTCentrePnl = new HQAddTCentrePnl(frame);
        frame.navigateContentPanel(addTCentrePnl);
    }

    public HQTCentreRightMenu(HQPanelContainer frame, int indicator) {
        initComponents();
        this.frame = frame;

        frame.navigateContentPanel(new HQSearchTCentrePnl(frame));

        // Change the GUI button colour
        if (indicator == 1) {
            pnlSearchTCentre.setBackground(new Color(63,91,135));
            pnlAddTCentre.setBackground(new Color(39,56,83));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightMenu = new javax.swing.JPanel();
        pnlAddTCentre = new javax.swing.JPanel();
        lblAddTCentre = new javax.swing.JLabel();
        pnlSearchTCentre = new javax.swing.JPanel();
        lblSearchTCentre = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlAddTCentre.setBackground(new java.awt.Color(63, 91, 135));
        pnlAddTCentre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddTCentreMouseClicked(evt);
            }
        });

        lblAddTCentre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddTCentre.setForeground(new java.awt.Color(255, 255, 255));
        lblAddTCentre.setText("Add Tuition Centre");

        javax.swing.GroupLayout pnlAddTCentreLayout = new javax.swing.GroupLayout(pnlAddTCentre);
        pnlAddTCentre.setLayout(pnlAddTCentreLayout);
        pnlAddTCentreLayout.setHorizontalGroup(
            pnlAddTCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddTCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAddTCentre)
                .addGap(55, 55, 55))
        );
        pnlAddTCentreLayout.setVerticalGroup(
            pnlAddTCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddTCentreLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAddTCentre)
                .addGap(17, 17, 17))
        );

        pnlSearchTCentre.setBackground(new java.awt.Color(39, 56, 83));
        pnlSearchTCentre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSearchTCentreMouseClicked(evt);
            }
        });

        lblSearchTCentre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchTCentre.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchTCentre.setText("Search Tuition Centre");

        javax.swing.GroupLayout pnlSearchTCentreLayout = new javax.swing.GroupLayout(pnlSearchTCentre);
        pnlSearchTCentre.setLayout(pnlSearchTCentreLayout);
        pnlSearchTCentreLayout.setHorizontalGroup(
            pnlSearchTCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchTCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblSearchTCentre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchTCentreLayout.setVerticalGroup(
            pnlSearchTCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTCentreLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSearchTCentre)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGroup(pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSearchTCentre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddTCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(pnlAddTCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSearchTCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlSearchTCentreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSearchTCentreMouseClicked
        pnlSearchTCentre.setBackground(new Color(63,91,135));
        pnlAddTCentre.setBackground(new Color(39,56,83));

        HQSearchTCentrePnl searchTCentrePnl = new HQSearchTCentrePnl(frame);
        frame.navigateContentPanel(searchTCentrePnl);
    }//GEN-LAST:event_pnlSearchTCentreMouseClicked

    private void pnlAddTCentreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddTCentreMouseClicked
        pnlAddTCentre.setBackground(new Color(63,91,135));
        pnlSearchTCentre.setBackground(new Color(39,56,83));

        HQAddTCentrePnl addTCentrePnl = new HQAddTCentrePnl(frame);
        frame.navigateContentPanel(addTCentrePnl);
    }//GEN-LAST:event_pnlAddTCentreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddTCentre;
    private javax.swing.JLabel lblSearchTCentre;
    private javax.swing.JPanel pnlAddTCentre;
    private javax.swing.JPanel pnlRightMenu;
    private javax.swing.JPanel pnlSearchTCentre;
    // End of variables declaration//GEN-END:variables
}
