package gui.hq.tcentre;

import gui.HQPanelContainer;

public class HQTCentreRightMenuSecondVer extends javax.swing.JPanel {
    private HQPanelContainer frame;

    public HQTCentreRightMenuSecondVer(HQPanelContainer frame) {
        initComponents();
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightMenu = new javax.swing.JPanel();
        pnlAddTCentre = new javax.swing.JPanel();
        lblAddTCentre = new javax.swing.JLabel();
        pnlBackToSearch = new javax.swing.JPanel();
        lblBackToSearch = new javax.swing.JLabel();
        lblIconBack = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlAddTCentre.setBackground(new java.awt.Color(39, 56, 83));
        pnlAddTCentre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddTCentreMouseClicked(evt);
            }
        });

        lblAddTCentre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddTCentre.setForeground(new java.awt.Color(255, 255, 255));
        lblAddTCentre.setText("Add Tuition Centre");

        javax.swing.GroupLayout pnlAddTCentreLayout = new javax.swing.GroupLayout(pnlAddTCentre);
        pnlAddTCentre.setLayout(pnlAddTCentreLayout);
        pnlAddTCentreLayout.setHorizontalGroup(
            pnlAddTCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddTCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAddTCentre)
                .addGap(55, 55, 55))
        );
        pnlAddTCentreLayout.setVerticalGroup(
            pnlAddTCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddTCentreLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAddTCentre)
                .addGap(17, 17, 17))
        );

        pnlBackToSearch.setBackground(new java.awt.Color(63, 91, 135));
        pnlBackToSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBackToSearchMouseClicked(evt);
            }
        });

        lblBackToSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBackToSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblBackToSearch.setText("Back to Search");

        lblIconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/icon_back.png"))); // NOI18N

        javax.swing.GroupLayout pnlBackToSearchLayout = new javax.swing.GroupLayout(pnlBackToSearch);
        pnlBackToSearch.setLayout(pnlBackToSearchLayout);
        pnlBackToSearchLayout.setHorizontalGroup(
            pnlBackToSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackToSearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblIconBack)
                .addGap(14, 14, 14)
                .addComponent(lblBackToSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackToSearchLayout.setVerticalGroup(
            pnlBackToSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackToSearchLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlBackToSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBackToSearch)
                    .addComponent(lblIconBack))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addComponent(pnlAddTCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(pnlBackToSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(pnlAddTCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBackToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddTCentreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddTCentreMouseClicked
        frame.navigateContentPanel(new HQAddTCentrePnl(frame));
        frame.navigateMenuPanel(new HQTCentreRightMenu(frame));
    }//GEN-LAST:event_pnlAddTCentreMouseClicked

    private void pnlBackToSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackToSearchMouseClicked
        frame.navigateContentPanel(new HQSearchTCentrePnl(frame));
        frame.navigateMenuPanel(new HQTCentreRightMenu(frame,1));
    }//GEN-LAST:event_pnlBackToSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddTCentre;
    private javax.swing.JLabel lblBackToSearch;
    private javax.swing.JLabel lblIconBack;
    private javax.swing.JPanel pnlAddTCentre;
    private javax.swing.JPanel pnlBackToSearch;
    private javax.swing.JPanel pnlRightMenu;
    // End of variables declaration//GEN-END:variables
}
