package gui.hq.payment;

import gui.HQPanelContainer;

import java.awt.Color;

public class HQPaymentRightMenu extends javax.swing.JPanel {
    private HQPanelContainer frame;

    public HQPaymentRightMenu(HQPanelContainer frame) {
        initComponents();
        this.frame = frame;
        
        frame.navigateContentPanel(new HQAddPaymentPnl(frame));
    }

    public HQPaymentRightMenu(HQPanelContainer frame, int indicator) {
        initComponents();
        this.frame = frame;
        
        frame.navigateContentPanel(new HQSearchPaymentPnl(frame));
        
        //Change the GUI button colour
        if(indicator == 1){
            pnlPaymentRecord.setBackground(new Color(63,91,135));
            pnlAddPayment.setBackground(new Color(39,56,83));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightMenu = new javax.swing.JPanel();
        pnlAddPayment = new javax.swing.JPanel();
        lblAddPayment = new javax.swing.JLabel();
        pnlPaymentRecord = new javax.swing.JPanel();
        lblPaymentRecord = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlAddPayment.setBackground(new java.awt.Color(63, 91, 135));
        pnlAddPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddPaymentMouseClicked(evt);
            }
        });

        lblAddPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblAddPayment.setText("Add Payment");

        javax.swing.GroupLayout pnlAddPaymentLayout = new javax.swing.GroupLayout(pnlAddPayment);
        pnlAddPayment.setLayout(pnlAddPaymentLayout);
        pnlAddPaymentLayout.setHorizontalGroup(
            pnlAddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddPaymentLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblAddPayment)
                .addGap(55, 55, 55))
        );
        pnlAddPaymentLayout.setVerticalGroup(
            pnlAddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddPaymentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAddPayment)
                .addGap(17, 17, 17))
        );

        pnlPaymentRecord.setBackground(new java.awt.Color(39, 56, 83));
        pnlPaymentRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPaymentRecordMouseClicked(evt);
            }
        });

        lblPaymentRecord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPaymentRecord.setForeground(new java.awt.Color(255, 255, 255));
        lblPaymentRecord.setText("Payment Record");

        javax.swing.GroupLayout pnlPaymentRecordLayout = new javax.swing.GroupLayout(pnlPaymentRecord);
        pnlPaymentRecord.setLayout(pnlPaymentRecordLayout);
        pnlPaymentRecordLayout.setHorizontalGroup(
            pnlPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentRecordLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblPaymentRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentRecordLayout.setVerticalGroup(
            pnlPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentRecordLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblPaymentRecord)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPaymentRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightMenuLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(pnlAddPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddPaymentMouseClicked
        pnlAddPayment.setBackground(new Color(63,91,135));
        pnlPaymentRecord.setBackground(new Color(39,56,83));
        
        frame.navigateContentPanel(new HQAddPaymentPnl(frame));
    }//GEN-LAST:event_pnlAddPaymentMouseClicked

    private void pnlPaymentRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaymentRecordMouseClicked
        pnlPaymentRecord.setBackground(new Color(63,91,135));
        pnlAddPayment.setBackground(new Color(39,56,83));
        
        frame.navigateContentPanel(new HQSearchPaymentPnl(frame));
    }//GEN-LAST:event_pnlPaymentRecordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddPayment;
    private javax.swing.JLabel lblPaymentRecord;
    private javax.swing.JPanel pnlAddPayment;
    private javax.swing.JPanel pnlPaymentRecord;
    private javax.swing.JPanel pnlRightMenu;
    // End of variables declaration//GEN-END:variables
}
