package gui.hq.payment;

import gui.HQPanelContainer;

import java.time.format.DateTimeFormatter;

import tutormanagementsystem.Branch;
import tutormanagementsystem.Main;
import tutormanagementsystem.Payment;
import tutormanagementsystem.Tutor;

public class HQPaymentDetailsPnl extends javax.swing.JPanel {
    private Tutor tutor;
    private Branch branch;

    public HQPaymentDetailsPnl(Payment payment) {
        initComponents();
        tutor = Main.tutorDatabase.findData(payment.getTutorId());
        branch = Main.branchDatabase.findData(tutor.getBranchId());

        // Populate text fields
        lblId.setText(String.format("%.0f", payment.getId()));
        lblTitle.setText(payment.getTitle());
        lblBranch.setText(branch.getName());
        lblTutorId.setText(String.format("%.0f", tutor.getId()));
        lblTutorName.setText(tutor.getName());

        lblAttendedHours.setText(String.valueOf(payment.getAttendedHours()) + " hrs");
        lblPayRate.setText("RM " + String.format("%.2f", tutor.getPayRate()));
        lblAmount.setText("RM " + String.format("%.2f", payment.getAmount()));
        lblTotalAmount.setText("RM " + String.format("%.2f", payment.getAmount()));

        lblDate.setText(payment.getPaymentDateTime().format(Main.DATE_FORMATTER));
        lblBankName.setText(tutor.getBankName());
        lblAccountName.setText(tutor.getAccountName());
        lblBankNumber.setText(tutor.getBankNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlPaymentRecord = new javax.swing.JPanel();
        lblPaymentRecord = new javax.swing.JLabel();
        pnlPaymentSection1 = new javax.swing.JPanel();
        lblIdTitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblTitleTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblBranchTitle = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblTutorIdTitle = new javax.swing.JLabel();
        lblTutorId = new javax.swing.JLabel();
        lblTutorNameTitle = new javax.swing.JLabel();
        lblTutorName = new javax.swing.JLabel();
        pnlPaymentSection2 = new javax.swing.JPanel();
        pnlAttendedHours = new javax.swing.JPanel();
        lblAttendedHoursTitle = new javax.swing.JLabel();
        lblAttendedHours = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        pnlPayRate = new javax.swing.JPanel();
        lblPayRateTitle = new javax.swing.JLabel();
        lblPayRate = new javax.swing.JLabel();
        lblTotalDecoration = new javax.swing.JLabel();
        pnlAmount = new javax.swing.JPanel();
        lblAmountTitle = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        pnlPaymentSection3 = new javax.swing.JPanel();
        lblDateTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblBankNameTitle = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblAccountNameTitle = new javax.swing.JLabel();
        lblAccountName = new javax.swing.JLabel();
        lblBankNumberTitle = new javax.swing.JLabel();
        lblBankNumber = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlPaymentRecord.setBackground(new java.awt.Color(242, 242, 242));
        pnlPaymentRecord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlPaymentRecord.setMaximumSize(null);

        lblPaymentRecord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPaymentRecord.setText("Payment Record");

        pnlPaymentSection1.setBackground(new java.awt.Color(230, 230, 230));

        lblIdTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdTitle.setText("Payment ID                      :");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTitleTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitleTitle.setText("Title                                  :");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblBranchTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBranchTitle.setText("Branch                              :");

        lblBranch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTutorIdTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTutorIdTitle.setText("Tutor ID                            :");

        lblTutorId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTutorNameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTutorNameTitle.setText("Tutor Name                      :");

        lblTutorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlPaymentSection1Layout = new javax.swing.GroupLayout(pnlPaymentSection1);
        pnlPaymentSection1.setLayout(pnlPaymentSection1Layout);
        pnlPaymentSection1Layout.setHorizontalGroup(
            pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentSection1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblBranchTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTutorNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTutorIdTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPaymentSection1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTutorId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTutorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentSection1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentSection1Layout.setVerticalGroup(
            pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentSection1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdTitle)
                    .addComponent(lblId))
                .addGap(6, 6, 6)
                .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleTitle)
                    .addComponent(lblTitle))
                .addGap(6, 6, 6)
                .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranchTitle)
                    .addComponent(lblBranch))
                .addGap(6, 6, 6)
                .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTutorIdTitle)
                    .addComponent(lblTutorId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPaymentSection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTutorNameTitle)
                    .addComponent(lblTutorName))
                .addGap(6, 6, 6))
        );

        pnlPaymentSection2.setBackground(new java.awt.Color(242, 242, 242));

        pnlAttendedHours.setBackground(new java.awt.Color(230, 230, 230));

        lblAttendedHoursTitle.setBackground(new java.awt.Color(39, 56, 83));
        lblAttendedHoursTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAttendedHoursTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendedHoursTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttendedHoursTitle.setText("Attended Hours");
        lblAttendedHoursTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblAttendedHoursTitle.setOpaque(true);

        lblAttendedHours.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblAttendedHours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTotal.setBackground(new java.awt.Color(217, 217, 217));
        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        lblTotal.setOpaque(true);

        javax.swing.GroupLayout pnlAttendedHoursLayout = new javax.swing.GroupLayout(pnlAttendedHours);
        pnlAttendedHours.setLayout(pnlAttendedHoursLayout);
        pnlAttendedHoursLayout.setHorizontalGroup(
            pnlAttendedHoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAttendedHoursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAttendedHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAttendedHoursLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(pnlAttendedHoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAttendedHoursTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlAttendedHoursLayout.setVerticalGroup(
            pnlAttendedHoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendedHoursLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblAttendedHoursTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAttendedHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlPayRate.setBackground(new java.awt.Color(230, 230, 230));

        lblPayRateTitle.setBackground(new java.awt.Color(39, 56, 83));
        lblPayRateTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPayRateTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPayRateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPayRateTitle.setText("Hourly Pay Rate");
        lblPayRateTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPayRateTitle.setOpaque(true);

        lblPayRate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPayRate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTotalDecoration.setBackground(new java.awt.Color(217, 217, 217));
        lblTotalDecoration.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalDecoration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalDecoration.setOpaque(true);

        javax.swing.GroupLayout pnlPayRateLayout = new javax.swing.GroupLayout(pnlPayRate);
        pnlPayRate.setLayout(pnlPayRateLayout);
        pnlPayRateLayout.setHorizontalGroup(
            pnlPayRateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPayRateTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPayRateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPayRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblTotalDecoration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPayRateLayout.setVerticalGroup(
            pnlPayRateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayRateLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPayRateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPayRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalDecoration, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlAmount.setBackground(new java.awt.Color(230, 230, 230));

        lblAmountTitle.setBackground(new java.awt.Color(39, 56, 83));
        lblAmountTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAmountTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAmountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmountTitle.setText("Amount");
        lblAmountTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblAmountTitle.setOpaque(true);

        lblAmount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTotalAmount.setBackground(new java.awt.Color(217, 217, 217));
        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalAmount.setOpaque(true);

        javax.swing.GroupLayout pnlAmountLayout = new javax.swing.GroupLayout(pnlAmount);
        pnlAmount.setLayout(pnlAmountLayout);
        pnlAmountLayout.setHorizontalGroup(
            pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAmountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAmountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlAmountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAmountLayout.setVerticalGroup(
            pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmountLayout.createSequentialGroup()
                .addComponent(lblAmountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlPaymentSection2Layout = new javax.swing.GroupLayout(pnlPaymentSection2);
        pnlPaymentSection2.setLayout(pnlPaymentSection2Layout);
        pnlPaymentSection2Layout.setHorizontalGroup(
            pnlPaymentSection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentSection2Layout.createSequentialGroup()
                .addComponent(pnlAttendedHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPayRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPaymentSection2Layout.setVerticalGroup(
            pnlPaymentSection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentSection2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlPaymentSection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAttendedHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPayRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlPaymentSection3.setBackground(new java.awt.Color(230, 230, 230));
        pnlPaymentSection3.setMaximumSize(new java.awt.Dimension(376, 118));
        pnlPaymentSection3.setMinimumSize(new java.awt.Dimension(376, 118));

        lblDateTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDateTitle.setText("Payment Date                :");

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblBankNameTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBankNameTitle.setText("Bank Name                    :");

        lblBankName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblAccountNameTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAccountNameTitle.setText("Account Name               :");

        lblAccountName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblBankNumberTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBankNumberTitle.setText("Bank Number                 :");

        lblBankNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlPaymentSection3Layout = new javax.swing.GroupLayout(pnlPaymentSection3);
        pnlPaymentSection3.setLayout(pnlPaymentSection3Layout);
        pnlPaymentSection3Layout.setHorizontalGroup(
            pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentSection3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDateTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAccountNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBankNumberTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBankNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate)
                    .addComponent(lblBankName)
                    .addComponent(lblAccountName)
                    .addComponent(lblBankNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentSection3Layout.setVerticalGroup(
            pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentSection3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateTitle)
                    .addComponent(lblDate))
                .addGap(10, 10, 10)
                .addGroup(pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBankNameTitle)
                    .addComponent(lblBankName))
                .addGap(10, 10, 10)
                .addGroup(pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccountNameTitle)
                    .addComponent(lblAccountName))
                .addGap(10, 10, 10)
                .addGroup(pnlPaymentSection3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankNumberTitle)
                    .addComponent(lblBankNumber))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPaymentRecordLayout = new javax.swing.GroupLayout(pnlPaymentRecord);
        pnlPaymentRecord.setLayout(pnlPaymentRecordLayout);
        pnlPaymentRecordLayout.setHorizontalGroup(
            pnlPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentRecordLayout.createSequentialGroup()
                .addGroup(pnlPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPaymentRecordLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblPaymentRecord))
                    .addGroup(pnlPaymentRecordLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlPaymentSection3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPaymentSection2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPaymentSection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlPaymentRecordLayout.setVerticalGroup(
            pnlPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentRecordLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblPaymentRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPaymentSection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlPaymentSection2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlPaymentSection3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(27, 27, 27)
                .addComponent(pnlPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccountName;
    private javax.swing.JLabel lblAccountNameTitle;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmountTitle;
    private javax.swing.JLabel lblAttendedHours;
    private javax.swing.JLabel lblAttendedHoursTitle;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankNameTitle;
    private javax.swing.JLabel lblBankNumber;
    private javax.swing.JLabel lblBankNumberTitle;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblBranchTitle;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateTitle;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdTitle;
    private javax.swing.JLabel lblPayRate;
    private javax.swing.JLabel lblPayRateTitle;
    private javax.swing.JLabel lblPaymentRecord;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTotalDecoration;
    private javax.swing.JLabel lblTutorId;
    private javax.swing.JLabel lblTutorIdTitle;
    private javax.swing.JLabel lblTutorName;
    private javax.swing.JLabel lblTutorNameTitle;
    private javax.swing.JPanel pnlAmount;
    private javax.swing.JPanel pnlAttendedHours;
    private javax.swing.JPanel pnlPayRate;
    private javax.swing.JPanel pnlPaymentRecord;
    private javax.swing.JPanel pnlPaymentSection1;
    private javax.swing.JPanel pnlPaymentSection2;
    private javax.swing.JPanel pnlPaymentSection3;
    private javax.swing.JPanel pnlRightBg;
    // End of variables declaration//GEN-END:variables
}
