package gui.hq.payment;

import gui.HQPanelContainer;

public class HQPaymentRightMenuSecondVer extends javax.swing.JPanel {
    private HQPanelContainer frame;

    public HQPaymentRightMenuSecondVer(HQPanelContainer frame) {
        initComponents();
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightMenu = new javax.swing.JPanel();
        pnlAddPayment = new javax.swing.JPanel();
        lblAddPayment = new javax.swing.JLabel();
        pnlBackToSearch = new javax.swing.JPanel();
        lblBackToSearchTutor = new javax.swing.JLabel();
        lblIconBack = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlAddPayment.setBackground(new java.awt.Color(39, 56, 83));
        pnlAddPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddPaymentMouseClicked(evt);
            }
        });

        lblAddPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblAddPayment.setText("Add Payment");

        javax.swing.GroupLayout pnlAddPaymentLayout = new javax.swing.GroupLayout(pnlAddPayment);
        pnlAddPayment.setLayout(pnlAddPaymentLayout);
        pnlAddPaymentLayout.setHorizontalGroup(
            pnlAddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddPaymentLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblAddPayment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddPaymentLayout.setVerticalGroup(
            pnlAddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddPaymentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAddPayment)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlBackToSearch.setBackground(new java.awt.Color(63, 91, 135));
        pnlBackToSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBackToSearchMouseClicked(evt);
            }
        });

        lblBackToSearchTutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBackToSearchTutor.setForeground(new java.awt.Color(255, 255, 255));
        lblBackToSearchTutor.setText("Back to Search");

        lblIconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/icon_back.png"))); // NOI18N

        javax.swing.GroupLayout pnlBackToSearchLayout = new javax.swing.GroupLayout(pnlBackToSearch);
        pnlBackToSearch.setLayout(pnlBackToSearchLayout);
        pnlBackToSearchLayout.setHorizontalGroup(
            pnlBackToSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackToSearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblIconBack)
                .addGap(14, 14, 14)
                .addComponent(lblBackToSearchTutor)
                .addGap(58, 58, 58))
        );
        pnlBackToSearchLayout.setVerticalGroup(
            pnlBackToSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackToSearchLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlBackToSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBackToSearchTutor)
                    .addComponent(lblIconBack))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackToSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAddPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightMenuLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(pnlAddPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBackToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddPaymentMouseClicked
        frame.navigateContentPanel(new HQAddPaymentPnl(frame));
        frame.navigateMenuPanel(new HQPaymentRightMenu(frame));
    }//GEN-LAST:event_pnlAddPaymentMouseClicked

    private void pnlBackToSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackToSearchMouseClicked
        frame.navigateContentPanel(new HQSearchPaymentPnl(frame));
        frame.navigateMenuPanel(new HQPaymentRightMenu(frame,1));
    }//GEN-LAST:event_pnlBackToSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddPayment;
    private javax.swing.JLabel lblBackToSearchTutor;
    private javax.swing.JLabel lblIconBack;
    private javax.swing.JPanel pnlAddPayment;
    private javax.swing.JPanel pnlBackToSearch;
    private javax.swing.JPanel pnlRightMenu;
    // End of variables declaration//GEN-END:variables
}
