package gui.tcentre.tutor;

import gui.TCentrePanelContainer;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tutormanagementsystem.Branch;
import tutormanagementsystem.Main;
import tutormanagementsystem.Tutor;

public class TCentreEditTutorPnl extends javax.swing.JPanel {
    private TCentrePanelContainer frame;
    private Branch branch;
    private Tutor tutor;

    public TCentreEditTutorPnl(TCentrePanelContainer frame, Branch branch, Tutor tutor) {
        initComponents();
        this.frame = frame;
        this.branch = branch;
        this.tutor = tutor;

        // Populate text fields
        txtTutorID.setText(String.format("%.0f", tutor.getId()));
        txtName.setText(tutor.getName());
        txtIdentityNumber.setText(tutor.getIdentityNumber());
        txtEmail.setText(tutor.getEmail());
        txtPhoneNumber.setText(tutor.getPhoneNumber());

        txtBranchName.setText(branch.getName());
        populateCmbSubjects();
        cmbSubjects.setSelectedItem(Main.subjectDatabase.findData(tutor.getSubjectIds()[0]).getName());
        txtPayRate.setText(String.format("%.2f", tutor.getPayRate()));
        txtJoinDate.setText(tutor.getJoinDate().format(Main.DATE_FORMATTER));
        if (!tutor.getTerminationDate().equals(LocalDate.MIN)) {
            txtTerminatedDate.setText(tutor.getTerminationDate().format(Main.DATE_FORMATTER));
        }

        txtBankName.setText(tutor.getBankName());
        txtAccountName.setText(tutor.getAccountName());
        txtBankNumber.setText(tutor.getBankNumber());
    }

    // Populate combobox data
    private void populateCmbSubjects() {
        // Remove existing combobox items
        cmbSubjects.removeAllItems();

        for (int i = 0; i < Main.subjectDatabase.getSize(); i++) {
            cmbSubjects.addItem(Main.subjectDatabase.getData(i).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlUpdateProfileContainer = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        tabpnlProfile = new javax.swing.JTabbedPane();
        pnlPersonalDetails = new javax.swing.JPanel();
        lblTutorID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblIdentityNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtTutorID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtIdentityNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        pnlBranchDetails = new javax.swing.JPanel();
        lblBranchName = new javax.swing.JLabel();
        lblSubjects = new javax.swing.JLabel();
        lblPayRate = new javax.swing.JLabel();
        lblJoinDate = new javax.swing.JLabel();
        lblTerminatedDate = new javax.swing.JLabel();
        txtBranchName = new javax.swing.JTextField();
        txtPayRate = new javax.swing.JTextField();
        txtJoinDate = new javax.swing.JTextField();
        txtTerminatedDate = new javax.swing.JTextField();
        cmbSubjects = new javax.swing.JComboBox<>();
        pnlBankAccountDetails = new javax.swing.JPanel();
        lblBankName = new javax.swing.JLabel();
        lblAccountName = new javax.swing.JLabel();
        lblBankNumber = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        txtAccountName = new javax.swing.JTextField();
        txtBankNumber = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlUpdateProfileContainer.setBackground(new java.awt.Color(242, 242, 242));
        pnlUpdateProfileContainer.setMinimumSize(new java.awt.Dimension(500, 450));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 43));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tabpnlProfile.setBackground(new java.awt.Color(51, 51, 51));

        pnlPersonalDetails.setBackground(new java.awt.Color(230, 230, 230));

        lblTutorID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTutorID.setText("Tutor ID");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblName.setText("Name");

        lblIdentityNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblIdentityNumber.setText("IC Number");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblEmail.setText("Email");

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        txtTutorID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTutorID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTutorID.setEnabled(false);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtIdentityNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setMaximumSize(new java.awt.Dimension(190, 26));
        txtEmail.setMinimumSize(new java.awt.Dimension(190, 26));

        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlPersonalDetailsLayout = new javax.swing.GroupLayout(pnlPersonalDetails);
        pnlPersonalDetails.setLayout(pnlPersonalDetailsLayout);
        pnlPersonalDetailsLayout.setHorizontalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTutorID)
                    .addComponent(lblName)
                    .addComponent(lblIdentityNumber)
                    .addComponent(lblEmail)
                    .addComponent(lblPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdentityNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTutorID, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(33, 33, 33))
        );
        pnlPersonalDetailsLayout.setVerticalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTutorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTutorID))
                .addGap(28, 28, 28)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentityNumber)
                    .addComponent(txtIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        tabpnlProfile.addTab("Personal Details", pnlPersonalDetails);

        pnlBranchDetails.setBackground(new java.awt.Color(230, 230, 230));

        lblBranchName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBranchName.setText("Allocated branch");

        lblSubjects.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblSubjects.setText("Subjects Taught");

        lblPayRate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPayRate.setText("Hourly Pay Rate");

        lblJoinDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblJoinDate.setText("Join Date");

        lblTerminatedDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTerminatedDate.setText("Terminated Date");

        txtBranchName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBranchName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBranchName.setEnabled(false);

        txtPayRate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtJoinDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtJoinDate.setEnabled(false);
        txtJoinDate.setMaximumSize(new java.awt.Dimension(190, 26));
        txtJoinDate.setMinimumSize(new java.awt.Dimension(190, 26));

        txtTerminatedDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTerminatedDate.setEnabled(false);

        cmbSubjects.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlBranchDetailsLayout = new javax.swing.GroupLayout(pnlBranchDetails);
        pnlBranchDetails.setLayout(pnlBranchDetailsLayout);
        pnlBranchDetailsLayout.setHorizontalGroup(
            pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBranchDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranchName)
                    .addComponent(lblSubjects)
                    .addComponent(lblPayRate)
                    .addComponent(lblJoinDate)
                    .addComponent(lblTerminatedDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPayRate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJoinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerminatedDate)
                    .addComponent(cmbSubjects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        pnlBranchDetailsLayout.setVerticalGroup(
            pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBranchDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchName))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubjects)
                    .addComponent(cmbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayRate)
                    .addComponent(txtPayRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoinDate)
                    .addComponent(txtJoinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBranchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminatedDate)
                    .addComponent(txtTerminatedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        tabpnlProfile.addTab("Branch Details", pnlBranchDetails);

        pnlBankAccountDetails.setBackground(new java.awt.Color(230, 230, 230));

        lblBankName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBankName.setText("Bank Name");

        lblAccountName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAccountName.setText("Account Name");

        lblBankNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblBankNumber.setText("Bank Number");

        txtBankName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtAccountName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtAccountName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAccountName.setMaximumSize(new java.awt.Dimension(190, 26));
        txtAccountName.setMinimumSize(new java.awt.Dimension(190, 26));

        txtBankNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlBankAccountDetailsLayout = new javax.swing.GroupLayout(pnlBankAccountDetails);
        pnlBankAccountDetails.setLayout(pnlBankAccountDetailsLayout);
        pnlBankAccountDetailsLayout.setHorizontalGroup(
            pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBankAccountDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBankName)
                    .addComponent(lblAccountName)
                    .addComponent(lblBankNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBankNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        pnlBankAccountDetailsLayout.setVerticalGroup(
            pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBankAccountDetailsLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountName)
                    .addComponent(txtAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnlBankAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankNumber)
                    .addComponent(txtBankNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        tabpnlProfile.addTab("Bank Account Details", pnlBankAccountDetails);

        javax.swing.GroupLayout pnlUpdateProfileContainerLayout = new javax.swing.GroupLayout(pnlUpdateProfileContainer);
        pnlUpdateProfileContainer.setLayout(pnlUpdateProfileContainerLayout);
        pnlUpdateProfileContainerLayout.setHorizontalGroup(
            pnlUpdateProfileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateProfileContainerLayout.createSequentialGroup()
                .addGroup(pnlUpdateProfileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateProfileContainerLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdateProfileContainerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tabpnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlUpdateProfileContainerLayout.setVerticalGroup(
            pnlUpdateProfileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateProfileContainerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tabpnlProfile)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRightBgLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(pnlUpdateProfileContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(523, 523, 523))
            .addGroup(pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRightBgLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(pnlUpdateProfileContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!txtName.getText().isEmpty() && !txtIdentityNumber.getText().isEmpty() && !txtPhoneNumber.getText().isEmpty() && !txtEmail.getText().isEmpty() && !txtBankName.getText().isEmpty() && !txtAccountName.getText().isEmpty() && !txtBankNumber.getText().isEmpty() && !txtBranchName.getText().toString().isEmpty() && !txtPayRate.getText().isEmpty()) {
            // Get index of current tutor
            int index = Main.tutorDatabase.getIndex(tutor);

            // Set updated tutor data
            tutor.setName(txtName.getText());
            tutor.setIdentityNumber(txtIdentityNumber.getText());
            tutor.setEmail(txtEmail.getText());
            tutor.setPhoneNumber(txtPhoneNumber.getText());
            tutor.setSubjectIds(new double[] {cmbSubjects.getSelectedIndex() + 1});
            tutor.setPayRate(Double.parseDouble(txtPayRate.getText()));
            tutor.setBankName(txtBankName.getText());
            tutor.setAccountName(txtAccountName.getText());
            tutor.setBankNumber(txtBankNumber.getText());

            // Update data in SecureDatabase
            Main.tutorDatabase.updateData(index, tutor);

            // Display success message
            JOptionPane.showMessageDialog(new JFrame(), "Tutor Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Refresh the page
            frame.navigateMenuPanel(new TCentreTutorRightMenu(frame, branch, 1));
        } else {
            // Display error message
            JOptionPane.showMessageDialog(new JFrame(), "Fields Cannot Be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSubjects;
    private javax.swing.JLabel lblAccountName;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankNumber;
    private javax.swing.JLabel lblBranchName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdentityNumber;
    private javax.swing.JLabel lblJoinDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPayRate;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSubjects;
    private javax.swing.JLabel lblTerminatedDate;
    private javax.swing.JLabel lblTutorID;
    private javax.swing.JPanel pnlBankAccountDetails;
    private javax.swing.JPanel pnlBranchDetails;
    private javax.swing.JPanel pnlPersonalDetails;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JPanel pnlUpdateProfileContainer;
    private javax.swing.JTabbedPane tabpnlProfile;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtBankNumber;
    private javax.swing.JTextField txtBranchName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentityNumber;
    private javax.swing.JTextField txtJoinDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPayRate;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtTerminatedDate;
    private javax.swing.JTextField txtTutorID;
    // End of variables declaration//GEN-END:variables
}
