package gui.tcentre.tutor;

import gui.TCentrePanelContainer;
import java.awt.Color;
import tutormanagementsystem.Branch;

public class TCentreTutorRightMenu extends javax.swing.JPanel {
    private TCentrePanelContainer frame;
    private Branch branch;

    public TCentreTutorRightMenu(TCentrePanelContainer frame, Branch branch) {
        initComponents();
        this.frame = frame;
        this.branch = branch;
        
        frame.navigateContentPanel(new TCentreAddTutorPnl(frame, branch));
    }

     public TCentreTutorRightMenu(TCentrePanelContainer frame, Branch branch, int indicator) {
        initComponents();
        this.frame = frame;
        this.branch = branch;
        
        frame.navigateContentPanel(new TCentreSearchTutorPnl(frame, branch));
        
        // Change the GUI button colour
        if (indicator == 1) {
            pnlSearchTutor.setBackground(new Color(63,91,135));
            pnlAddTutor.setBackground(new Color(39,56,83));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightMenu = new javax.swing.JPanel();
        pnlAddTutor = new javax.swing.JPanel();
        lblAddTutor = new javax.swing.JLabel();
        pnlSearchTutor = new javax.swing.JPanel();
        lblSearchTutor = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightMenu.setBackground(new java.awt.Color(39, 56, 83));

        pnlAddTutor.setBackground(new java.awt.Color(63, 91, 135));
        pnlAddTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddTutorMouseClicked(evt);
            }
        });

        lblAddTutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddTutor.setForeground(new java.awt.Color(255, 255, 255));
        lblAddTutor.setText("Add Tutor");

        javax.swing.GroupLayout pnlAddTutorLayout = new javax.swing.GroupLayout(pnlAddTutor);
        pnlAddTutor.setLayout(pnlAddTutorLayout);
        pnlAddTutorLayout.setHorizontalGroup(
            pnlAddTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddTutorLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblAddTutor)
                .addGap(55, 55, 55))
        );
        pnlAddTutorLayout.setVerticalGroup(
            pnlAddTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddTutorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAddTutor)
                .addGap(17, 17, 17))
        );

        pnlSearchTutor.setBackground(new java.awt.Color(39, 56, 83));
        pnlSearchTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSearchTutorMouseClicked(evt);
            }
        });

        lblSearchTutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchTutor.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchTutor.setText("Search Tutor");

        javax.swing.GroupLayout pnlSearchTutorLayout = new javax.swing.GroupLayout(pnlSearchTutor);
        pnlSearchTutor.setLayout(pnlSearchTutorLayout);
        pnlSearchTutorLayout.setHorizontalGroup(
            pnlSearchTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchTutorLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblSearchTutor)
                .addGap(44, 44, 44))
        );
        pnlSearchTutorLayout.setVerticalGroup(
            pnlSearchTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTutorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSearchTutor)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRightMenuLayout = new javax.swing.GroupLayout(pnlRightMenu);
        pnlRightMenu.setLayout(pnlRightMenuLayout);
        pnlRightMenuLayout.setHorizontalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSearchTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRightMenuLayout.setVerticalGroup(
            pnlRightMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightMenuLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(pnlAddTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSearchTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        add(pnlRightMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddTutorMouseClicked
        pnlAddTutor.setBackground(new Color(63,91,135));
        pnlSearchTutor.setBackground(new Color(39,56,83));
        
        frame.navigateContentPanel(new TCentreAddTutorPnl(frame, branch));
    }//GEN-LAST:event_pnlAddTutorMouseClicked

    private void pnlSearchTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSearchTutorMouseClicked
        pnlSearchTutor.setBackground(new Color(63,91,135));
        pnlAddTutor.setBackground(new Color(39,56,83));
        
        frame.navigateContentPanel(new TCentreSearchTutorPnl(frame, branch));
    }//GEN-LAST:event_pnlSearchTutorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddTutor;
    private javax.swing.JLabel lblSearchTutor;
    private javax.swing.JPanel pnlAddTutor;
    private javax.swing.JPanel pnlRightMenu;
    private javax.swing.JPanel pnlSearchTutor;
    // End of variables declaration//GEN-END:variables
}
