package gui.tcentre.tutor;

import gui.TCentrePanelContainer;
import java.awt.Font;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tutormanagementsystem.Branch;
import tutormanagementsystem.Main;
import tutormanagementsystem.Tutor;

public class TCentreSearchTutorPnl extends javax.swing.JPanel {
    private TCentrePanelContainer frame;
    private Branch branch;

    public TCentreSearchTutorPnl(TCentrePanelContainer frame, Branch branch) {
        initComponents();
        this.frame = frame;
        this.branch = branch;

        populateTblTutor();
    }

    // Populate table data
    private void populateTblTutor() {
        // Get table model
        DefaultTableModel model = (DefaultTableModel) tblTutor.getModel();
        // Remove existing combobox items
        model.setRowCount(0);

        for (int i = 0; i < Main.tutorDatabase.getSize(); i++) {
            Tutor tutor = Main.tutorDatabase.getData(i);
            if (tutor.getBranchId() == branch.getId()) {
                model.addRow(new Object[] {String.format("%.0f", tutor.getId()), tutor.getName(), tutor.getPhoneNumber(), tutor.getEmail()});
            }
        }
    }

    // Filter data
    private void filter(String query){
        // Get table model and create sorter
        DefaultTableModel model = (DefaultTableModel) tblTutor.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblTutor.setRowSorter(sorter);

        // Filter the data
        if (query.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightBg = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlSearchTutorContainer = new javax.swing.JPanel();
        scrpnlTutorTable = new javax.swing.JScrollPane();
        tblTutor = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightBg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        pnlSearchTutorContainer.setBackground(new java.awt.Color(242, 242, 242));
        pnlSearchTutorContainer.setMinimumSize(new java.awt.Dimension(500, 450));

        scrpnlTutorTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrpnlTutorTable.setPreferredSize(new java.awt.Dimension(452, 200));

        tblTutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTutor.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblTutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone Num.", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTutorMouseClicked(evt);
            }
        });
        scrpnlTutorTable.setViewportView(tblTutor);
        if (tblTutor.getColumnModel().getColumnCount() > 0) {
            tblTutor.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblTutor.getColumnModel().getColumn(2).setPreferredWidth(35);
        }

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 0, 43));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("Select a tutor and press this.");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchTutorContainerLayout = new javax.swing.GroupLayout(pnlSearchTutorContainer);
        pnlSearchTutorContainer.setLayout(pnlSearchTutorContainerLayout);
        pnlSearchTutorContainerLayout.setHorizontalGroup(
            pnlSearchTutorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTutorContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSearchTutorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchTutorContainerLayout.createSequentialGroup()
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrpnlTutorTable, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlSearchTutorContainerLayout.setVerticalGroup(
            pnlSearchTutorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchTutorContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSearchTutorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(scrpnlTutorTable, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnlRightBgLayout = new javax.swing.GroupLayout(pnlRightBg);
        pnlRightBg.setLayout(pnlRightBgLayout);
        pnlRightBgLayout.setHorizontalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pnlSearchTutorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRightBgLayout.setVerticalGroup(
            pnlRightBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightBgLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(37, 37, 37)
                .addComponent(pnlSearchTutorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Exit button
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Get model of the table, then get selected row
        DefaultTableModel model = (DefaultTableModel) tblTutor.getModel();
        int selectedRowIndex = tblTutor.convertRowIndexToModel(tblTutor.getSelectedRow());

        // Get the tutorID
        double id = Double.parseDouble(model.getValueAt(selectedRowIndex, 0).toString());

        frame.navigateMenuPanel(new TCentreTutorRightMenuSecondVer(frame, branch));
        frame.navigateContentPanel(new TCentreEditTutorPnl(frame, branch, Main.tutorDatabase.findData(id)));
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // Get the input and call filter()
        String query = txtSearch.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblTutorMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // Enable edit button
        btnEdit.setEnabled(true);
    }                                     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblClose;
    private javax.swing.JPanel pnlRightBg;
    private javax.swing.JPanel pnlSearchTutorContainer;
    private javax.swing.JScrollPane scrpnlTutorTable;
    private javax.swing.JTable tblTutor;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
